=== Quodatum/xqlint/schemas/json-schema-temp.json
{
  "type": "array",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "description": "",
  "minItems": 1,
  "uniqueItems": true,
  "items": {
    "type": "object",
    "required": [
      "key",
      "type",
      "range",
      "selectionRange",
      "bcom",
      "xcom"
    ],
    "properties": {
      "key": {
        "type": "string",
        "minLength": 1
      },
      "type": {
        "type": "string",
        "minLength": 1
      },
      "range": {
        "type": "object",
        "properties": {
          "sl": {
            "type": "number"
          },
          "sc": {
            "type": "number"
          },
          "el": {
            "type": "number"
          },
          "ec": {
            "type": "number"
          }
        },
        "required": [
          "sl",
          "sc",
          "el",
          "ec"
        ]
      },
      "selectionRange": {
        "type": "object",
        "properties": {
          "sl": {
            "type": "number"
          },
          "sc": {
            "type": "number"
          },
          "el": {
            "type": "number"
          },
          "ec": {
            "type": "number"
          }
        },
        "required": [
          "sl",
          "sc",
          "el",
          "ec"
        ]
      },
      "bcom": {
        "type": "boolean"
      },
      "xcom": {
        "type": "boolean"
      }
    }
  }
}

=== Quodatum/xqlint/temp.json
[
  {
    "key": "org.expkg_zone58.Pdfbox3#with-pdf#2",
    "type": "FunctionDecl",
    "range": {
      "sl": 28,
      "sc": 44,
      "el": 46,
      "ec": 1
    },
    "selectionRange": {
      "sl": 36,
      "sc": 17,
      "el": 36,
      "ec": 32
    },
    "bcom": true,
    "xcom": true
  },
  {
    "key": "org.expkg_zone58.Pdfbox3#open#1",
    "type": "FunctionDecl",
    "range": {
      "sl": 46,
      "sc": 2,
      "el": 53,
      "ec": 1
    },
    "selectionRange": {
      "sl": 50,
      "sc": 17,
      "el": 50,
      "ec": 28
    },
    "bcom": true,
    "xcom": true
  },
  {
    "key": "org.expkg_zone58.Pdfbox3#open#2",
    "type": "FunctionDecl",
    "range": {
      "sl": 53,
      "sc": 2,
      "el": 75,
      "ec": 1
    },
    "selectionRange": {
      "sl": 59,
      "sc": 17,
      "el": 59,
      "ec": 28
    },
    "bcom": true,
    "xcom": true
  },
  {
    "key": "org.expkg_zone58.Pdfbox3#specification#1",
    "type": "FunctionDecl",
    "range": {
      "sl": 75,
      "sc": 2,
      "el": 83,
      "ec": 1
    },
    "selectionRange": {
      "sl": 80,
      "sc": 17,
      "el": 80,
      "ec": 37
    },
    "bcom": true,
    "xcom": true
  },
  {
    "key": "org.expkg_zone58.Pdfbox3#save#2",
    "type": "FunctionDecl",
    "range": {
      "sl": 83,
      "sc": 2,
      "el": 89,
      "ec": 1
    },
    "selectionRange": {
      "sl": 86,
      "sc": 17,
      "el": 86,
      "ec": 28
    },
    "bcom": true,
    "xcom": true
  },
  {
    "key": "org.expkg_zone58.Pdfbox3#binary#1",
    "type": "FunctionDecl",
    "range": {
      "sl": 89,
      "sc": 2,
      "el": 98,
      "ec": 1
    },
    "selectionRange": {
      "sl": 92,
      "sc": 17,
      "el": 92,
      "ec": 30
    },
    "bcom": true,
    "xcom": true
  },
  {
    "key": "org.expkg_zone58.Pdfbox3#close#1",
    "type": "FunctionDecl",
    "range": {
      "sl": 101,
      "sc": 0,
      "el": 106,
      "ec": 1
    },
    "selectionRange": {
      "sl": 101,
      "sc": 17,
      "el": 101,
      "ec": 29
    },
    "bcom": false,
    "xcom": false
  },
  {
    "key": "org.expkg_zone58.Pdfbox3#page-count#1",
    "type": "FunctionDecl",
    "range": {
      "sl": 106,
      "sc": 2,
      "el": 112,
      "ec": 1
    },
    "selectionRange": {
      "sl": 109,
      "sc": 17,
      "el": 109,
      "ec": 34
    },
    "bcom": true,
    "xcom": true
  },
  {
    "key": "org.expkg_zone58.Pdfbox3#page-image#3",
    "type": "FunctionDecl",
    "range": {
      "sl": 112,
      "sc": 2,
      "el": 125,
      "ec": 1
    },
    "selectionRange": {
      "sl": 116,
      "sc": 17,
      "el": 116,
      "ec": 34
    },
    "bcom": true,
    "xcom": true
  },
  {
    "key": "org.expkg_zone58.Pdfbox3#property-map",
    "type": "VarDecl",
    "range": {
      "sl": 125,
      "sc": 2,
      "el": 165,
      "ec": 1
    },
    "selectionRange": {
      "sl": 131,
      "sc": 27,
      "el": 131,
      "ec": 46
    },
    "bcom": true,
    "xcom": true
  },
  {
    "key": "org.expkg_zone58.Pdfbox3#defined-properties#0",
    "type": "FunctionDecl",
    "range": {
      "sl": 165,
      "sc": 2,
      "el": 171,
      "ec": 1
    },
    "selectionRange": {
      "sl": 168,
      "sc": 17,
      "el": 168,
      "ec": 42
    },
    "bcom": true,
    "xcom": true
  },
  {
    "key": "org.expkg_zone58.Pdfbox3#property#2",
    "type": "FunctionDecl",
    "range": {
      "sl": 171,
      "sc": 2,
      "el": 182,
      "ec": 1
    },
    "selectionRange": {
      "sl": 174,
      "sc": 17,
      "el": 174,
      "ec": 32
    },
    "bcom": true,
    "xcom": true
  },
  {
    "key": "org.expkg_zone58.Pdfbox3#report#1",
    "type": "FunctionDecl",
    "range": {
      "sl": 182,
      "sc": 2,
      "el": 189,
      "ec": 1
    },
    "selectionRange": {
      "sl": 186,
      "sc": 17,
      "el": 186,
      "ec": 30
    },
    "bcom": true,
    "xcom": true
  },
  {
    "key": "org.expkg_zone58.Pdfbox3#report#2",
    "type": "FunctionDecl",
    "range": {
      "sl": 189,
      "sc": 2,
      "el": 217,
      "ec": 1
    },
    "selectionRange": {
      "sl": 194,
      "sc": 17,
      "el": 194,
      "ec": 30
    },
    "bcom": true,
    "xcom": true
  },
  {
    "key": "org.expkg_zone58.Pdfbox3#hasOutline#1",
    "type": "FunctionDecl",
    "range": {
      "sl": 217,
      "sc": 2,
      "el": 225,
      "ec": 1
    },
    "selectionRange": {
      "sl": 220,
      "sc": 17,
      "el": 220,
      "ec": 34
    },
    "bcom": true,
    "xcom": true
  },
  {
    "key": "org.expkg_zone58.Pdfbox3#hasLabels#1",
    "type": "FunctionDecl",
    "range": {
      "sl": 225,
      "sc": 2,
      "el": 233,
      "ec": 1
    },
    "selectionRange": {
      "sl": 228,
      "sc": 17,
      "el": 228,
      "ec": 33
    },
    "bcom": true,
    "xcom": true
  },
  {
    "key": "org.expkg_zone58.Pdfbox3#outline#1",
    "type": "FunctionDecl",
    "range": {
      "sl": 233,
      "sc": 2,
      "el": 246,
      "ec": 1
    },
    "selectionRange": {
      "sl": 236,
      "sc": 17,
      "el": 236,
      "ec": 31
    },
    "bcom": true,
    "xcom": true
  },
  {
    "key": "org.expkg_zone58.Pdfbox3#outline#2",
    "type": "FunctionDecl",
    "range": {
      "sl": 246,
      "sc": 2,
      "el": 253,
      "ec": 1
    },
    "selectionRange": {
      "sl": 249,
      "sc": 17,
      "el": 249,
      "ec": 31
    },
    "bcom": true,
    "xcom": true
  },
  {
    "key": "org.expkg_zone58.Pdfbox3#outline_#2",
    "type": "FunctionDecl",
    "range": {
      "sl": 253,
      "sc": 2,
      "el": 275,
      "ec": 1
    },
    "selectionRange": {
      "sl": 256,
      "sc": 26,
      "el": 256,
      "ec": 41
    },
    "bcom": true,
    "xcom": true
  },
  {
    "key": "org.expkg_zone58.Pdfbox3#outline-xml#1",
    "type": "FunctionDecl",
    "range": {
      "sl": 275,
      "sc": 2,
      "el": 284,
      "ec": 1
    },
    "selectionRange": {
      "sl": 278,
      "sc": 17,
      "el": 278,
      "ec": 35
    },
    "bcom": true,
    "xcom": true
  },
  {
    "key": "org.expkg_zone58.Pdfbox3#bookmark-xml#1",
    "type": "FunctionDecl",
    "range": {
      "sl": 286,
      "sc": 0,
      "el": 293,
      "ec": 1
    },
    "selectionRange": {
      "sl": 286,
      "sc": 26,
      "el": 286,
      "ec": 45
    },
    "bcom": false,
    "xcom": false
  },
  {
    "key": "org.expkg_zone58.Pdfbox3#bookmark#2",
    "type": "FunctionDecl",
    "range": {
      "sl": 293,
      "sc": 2,
      "el": 307,
      "ec": 1
    },
    "selectionRange": {
      "sl": 298,
      "sc": 26,
      "el": 298,
      "ec": 41
    },
    "bcom": true,
    "xcom": true
  },
  {
    "key": "org.expkg_zone58.Pdfbox3#find-page#2",
    "type": "FunctionDecl",
    "range": {
      "sl": 307,
      "sc": 2,
      "el": 320,
      "ec": 1
    },
    "selectionRange": {
      "sl": 311,
      "sc": 17,
      "el": 311,
      "ec": 33
    },
    "bcom": true,
    "xcom": true
  },
  {
    "key": "org.expkg_zone58.Pdfbox3#extract#3",
    "type": "FunctionDecl",
    "range": {
      "sl": 320,
      "sc": 2,
      "el": 329,
      "ec": 1
    },
    "selectionRange": {
      "sl": 323,
      "sc": 17,
      "el": 323,
      "ec": 31
    },
    "bcom": true,
    "xcom": true
  },
  {
    "key": "org.expkg_zone58.Pdfbox3#labels#1",
    "type": "FunctionDecl",
    "range": {
      "sl": 329,
      "sc": 2,
      "el": 344,
      "ec": 1
    },
    "selectionRange": {
      "sl": 336,
      "sc": 17,
      "el": 336,
      "ec": 30
    },
    "bcom": true,
    "xcom": true
  },
  {
    "key": "org.expkg_zone58.Pdfbox3#page-text#2",
    "type": "FunctionDecl",
    "range": {
      "sl": 344,
      "sc": 2,
      "el": 355,
      "ec": 1
    },
    "selectionRange": {
      "sl": 347,
      "sc": 17,
      "el": 347,
      "ec": 33
    },
    "bcom": true,
    "xcom": true
  },
  {
    "key": "org.expkg_zone58.Pdfbox3#page-size#2",
    "type": "FunctionDecl",
    "range": {
      "sl": 355,
      "sc": 2,
      "el": 363,
      "ec": 1
    },
    "selectionRange": {
      "sl": 358,
      "sc": 17,
      "el": 358,
      "ec": 33
    },
    "bcom": true,
    "xcom": true
  },
  {
    "key": "org.expkg_zone58.Pdfbox3#version#0",
    "type": "FunctionDecl",
    "range": {
      "sl": 363,
      "sc": 2,
      "el": 369,
      "ec": 1
    },
    "selectionRange": {
      "sl": 366,
      "sc": 17,
      "el": 366,
      "ec": 31
    },
    "bcom": true,
    "xcom": true
  },
  {
    "key": "org.expkg_zone58.Pdfbox3#gregToISO#1",
    "type": "FunctionDecl",
    "range": {
      "sl": 369,
      "sc": 2,
      "el": 378,
      "ec": 1
    },
    "selectionRange": {
      "sl": 373,
      "sc": 9,
      "el": 373,
      "ec": 25
    },
    "bcom": true,
    "xcom": true
  },
  {
    "key": "org.expkg_zone58.Pdfbox3#do-until#3",
    "type": "FunctionDecl",
    "range": {
      "sl": 378,
      "sc": 2,
      "el": 397,
      "ec": 1
    },
    "selectionRange": {
      "sl": 383,
      "sc": 26,
      "el": 383,
      "ec": 41
    },
    "bcom": true,
    "xcom": true
  }
]

=== Quodatum/xqlint/pic.json
[
 {
  "key": "#year",
  "type": "VarDecl",
  "range": {
   "sl": 3,
   "sc": 0,
   "el": 3,
   "ec": 30
  },
  "selectionRange": {
   "sl": 3,
   "sc": 18,
   "el": 3,
   "ec": 22
  },
  "bcom": false,
  "xcom": false
 },
 {
  "key": "#base",
  "type": "VarDecl",
  "range": {
   "sl": 3,
   "sc": 31,
   "el": 5,
   "ec": 63
  },
  "selectionRange": {
   "sl": 5,
   "sc": 18,
   "el": 5,
   "ec": 22
  },
  "bcom": true,
  "xcom": true
 },
 {
  "key": "#folders",
  "type": "VarDecl",
  "range": {
   "sl": 6,
   "sc": 0,
   "el": 6,
   "ec": 96
  },
  "selectionRange": {
   "sl": 6,
   "sc": 18,
   "el": 6,
   "ec": 25
  },
  "bcom": false,
  "xcom": false
 },
 {
  "key": "http://www.w3.org/2005/xquery-local-functions#extract#2",
  "type": "FunctionDecl",
  "range": {
   "sl": 11,
   "sc": 0,
   "el": 17,
   "ec": 1
  },
  "selectionRange": {
   "sl": 11,
   "sc": 17,
   "el": 11,
   "ec": 30
  },
  "bcom": true,
  "xcom": true
 },
 {
  "key": "http://www.w3.org/2005/xquery-local-functions#date-wrong#2",
  "type": "FunctionDecl",
  "range": {
   "sl": 22,
   "sc": 0,
   "el": 32,
   "ec": 1
  },
  "selectionRange": {
   "sl": 22,
   "sc": 17,
   "el": 22,
   "ec": 33
  },
  "bcom": true,
  "xcom": true
 },
 {
  "key": "http://www.w3.org/2005/xquery-local-functions#move#2",
  "type": "FunctionDecl",
  "range": {
   "sl": 35,
   "sc": 0,
   "el": 40,
   "ec": 1
  },
  "selectionRange": {
   "sl": 35,
   "sc": 17,
   "el": 35,
   "ec": 27
  },
  "bcom": true,
  "xcom": true
 },
 {
  "key": "http://www.w3.org/2005/xquery-local-functions#print#2",
  "type": "FunctionDecl",
  "range": {
   "sl": 42,
   "sc": 0,
   "el": 46,
   "ec": 1
  },
  "selectionRange": {
   "sl": 42,
   "sc": 17,
   "el": 42,
   "ec": 28
  },
  "bcom": false,
  "xcom": false
 },
 {
  "key": "http://www.w3.org/2005/xquery-local-functions#do#1",
  "type": "FunctionDecl",
  "range": {
   "sl": 48,
   "sc": 0,
   "el": 57,
   "ec": 1
  },
  "selectionRange": {
   "sl": 48,
   "sc": 17,
   "el": 48,
   "ec": 25
  },
  "bcom": false,
  "xcom": false
 },
 {
  "key": "QueryBody",
  "type": "QueryBody",
  "range": {
   "sl": 60,
   "sc": 0,
   "el": 63,
   "ec": 30
  },
  "selectionRange": {
   "sl": 60,
   "sc": 0,
   "el": 63,
   "ec": 30
  }
 }
]
